# Data Wrangling Assignment

## Problem Statement:
The objective of this assignment is to perform data wrangling operations on an open-source dataset using Python. The task includes importing required libraries, loading the dataset, performing data preprocessing, handling missing values, data formatting, normalization, and converting categorical variables into numerical form.

The dataset is taken from Kaggle:
https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset

The dataset contains information about loan applicants such as gender, income, loan amount, education, and loan status. The goal is to clean and transform the data to make it suitable for analysis and machine learning.

## Import Required Libraries

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

## Load Dataset

In [98]:
df = pd.read_csv('loan_data_set.csv')

## Display Dataset

In [10]:
# showing the first few rows from the dataset we can pass row_size to see the numbers of rows like this : df.head(10)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [13]:
# showing the las few rows from dataset
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

## Dataset Information Data Understanding

In [14]:
# Display shape (rows and columns) of Dataset
df.shape

(614, 13)

In [15]:
# Display structure of Dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [17]:
# Display column names
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='str')

##  Data Preprocessing

In [18]:
# Display datatypes of each columns
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [19]:
# Statistical summary of dataset
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [20]:
# Check missing values
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

## Data Formatting
Convert data into correct types

In [23]:
# check all column data types
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [28]:
# convert the string dataypes into the category
col = df.select_dtypes(include='str').columns
print(col)

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status'],
      dtype='str')

In [30]:
# select the Perticular column for conversion
col = ['Gender', 'Married','Education','Self_Employed', 'Property_Area', 'Loan_Status']

In [34]:
# conversion
for i in col:
    df[i]=df[i].astype('category')

In [35]:
df.dtypes

Loan_ID                   str
Gender               category
Married              category
Dependents                str
Education            category
Self_Employed        category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Loan_Amount_Term      float64
Credit_History        float64
Property_Area        category
Loan_Status          category
dtype: object

In [21]:
# convert the ApplicantIncome column int to float
df['ApplicantIncome'] = df['ApplicantIncome'].astype('float')

In [22]:
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [39]:
# convert the LoanAmount into integer
df['LoanAmount']= df['LoanAmount'].astype('Int64')

In [40]:
df.dtypes

Loan_ID                   str
Gender               category
Married              category
Dependents                str
Education            category
Self_Employed        category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount              Int64
Loan_Amount_Term      float64
Credit_History        float64
Property_Area        category
Loan_Status          category
dtype: object

## Data Normalization
Only numeric columns are normalized

In [41]:
# Show original values
df[['ApplicantIncome', 'LoanAmount']].head()

   ApplicantIncome  LoanAmount
0           5849.0        <NA>
1           4583.0         128
2           3000.0          66
3           2583.0         120
4           6000.0         141

In [42]:
# Using Min-Max Scaling
# formula  x' = (x- x_min)/(x_max - x_min)
df['ApplicantIncome_norm'] = ( df['ApplicantIncome']-df['ApplicantIncome'].min() ) / (df['ApplicantIncome'].max() - df['ApplicantIncome'].min())

In [44]:
df[['ApplicantIncome', 'ApplicantIncome_norm','LoanAmount']].head()

   ApplicantIncome  ApplicantIncome_norm  LoanAmount
0           5849.0              0.070489        <NA>
1           4583.0              0.054830         128
2           3000.0              0.035250          66
3           2583.0              0.030093         120
4           6000.0              0.072356         141

In [51]:
# Min-Max Scaling Using sklearn
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
df['LoanAmount_norm']= scaler.fit_transform(df[['LoanAmount']])

In [52]:
df[['ApplicantIncome', 'ApplicantIncome_norm','LoanAmount','LoanAmount_norm']].head()

   ApplicantIncome  ApplicantIncome_norm  LoanAmount  LoanAmount_norm
0           5849.0              0.070489        <NA>              NaN
1           4583.0              0.054830         128         0.172214
2           3000.0              0.035250          66         0.082489
3           2583.0              0.030093         120         0.160637
4           6000.0              0.072356         141         0.191027

In [53]:
# Z-score normalization
# formula : x' = x - mean / std

col = 'LoanAmount'

mean = df[col].mean()
std = df[col].std()

df[col + "_zscore"] = (df[col] - mean) / std

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,ApplicantIncome_norm,LoanAmount_norm,LoanAmount_zscore
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,<NA>,360.0,1.0,Urban,Y,0.070489,NaN,<NA>
1,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128,360.0,1.0,Rural,N,0.054830,0.172214,-0.215127
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66,360.0,1.0,Urban,Y,0.035250,0.082489,-0.939534
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120,360.0,1.0,Urban,Y,0.030093,0.160637,-0.308599
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141,360.0,1.0,Urban,Y,0.072356,0.191027,-0.063236

## Convert Categorical Variables

In [74]:
# Label Encoding using map function
df['Gender'] = df['Gender'].map({ 'Male' : 'M', 'Female' :'F'})

In [75]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,M,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,M,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,M,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,M,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,M,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [76]:
# Checking the Unique Values
df['Married'].unique()

<StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [83]:
df['Married_Encodeing']= df['Married'].map({'Yes':'Y','No':'N'})

In [84]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Married_Encodeing
0,LP001002,M,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,N
1,LP001003,M,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,Y
2,LP001005,M,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Y
3,LP001006,M,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,Y
4,LP001008,M,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,N

In [100]:
# Convert categorical columns using one-hot encoding

df = pd.get_dummies(df,columns=['Property_Area'],prefix='Property')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Rural,Property_Semiurban,Property_Urban
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Y,False,False,True
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,N,True,False,False
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Y,False,False,True
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Y,False,False,True
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Y,False,False,True