### Descriptive Statistics
Descriptive statistics are statistical methods used to summarize, organize, and describe the main features of a dataset. They provide a simple way to understand large amounts of data by presenting it in a meaningful form using numbers, tables, and graphs.

### Measures of Central Tendency

Measures of central tendency indicate the central or typical value of a dataset. They describe where most of the data values are concentrated.

1. Mean (Arithmetic Mean)

The mean is the average value of a dataset and is calculated by dividing the sum of all observations by the total number of observations.

2. Median

The median is the middle value of a dataset when the values are arranged in ascending or descending order.

If the number of observations is odd, the median is the middle value.
If even, it is the average of the two middle values.
    
3. Mode

The mode is the most frequently occurring value in a dataset. A dataset may have one mode, more than one mode, or no mode.

### Measures of Variability (Dispersion)

Measures of variability describe the spread or dispersion of data values around the central value.

1. Range

Range is the difference between the maximum and minimum values in a dataset.

Range=Maximum−Minimum

2. Variance

Variance measures how far each data point is from the mean. It is calculated as the average of squared differences from the mean.

3. Standard Deviation

Standard deviation is the square root of variance and indicates the average deviation of data points from the mean.

## Problem Statement

Perform descriptive statistical analysis on an open-source dataset.

A) Compute summary statistics (mean, median, minimum, maximum, standard deviation) for numerical variables grouped by a categorical variable. Also create a list of numeric values for each category.

B) Using the Iris dataset, display statistical measures such as mean, standard deviation, and percentiles for each species: Iris-setosa, Iris-versicolor, and Iris-virginica.

## Import required libraries

In [2]:
import pandas as pd
import numpy as np

## Load dataset

In [4]:
df = pd.read_csv("loan_data_set.csv")

## Display data

In [5]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

## Check column names and data types

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

## Group Data by Categorical Variable

In [11]:
# Group ApplicantIncome by Gender
grouped = df.groupby('Gender')['ApplicantIncome']

In [12]:
# Calculate mean, median, min, max, std
summary_stats = grouped.agg(['mean', 'median', 'min', 'max', 'std'])

print(summary_stats)

               mean  median  min    max          std
Gender
Female  4643.473214  3583.0  210  19484  3585.381488
Male    5446.460123  3865.0  150  81000  6185.789262

In [13]:
# Create list of incomes for each gender
income_list = df.groupby('Gender')['ApplicantIncome'].apply(list)

print(income_list)

Gender
Female    [3510, 3750, 3667, 3410, 2645, 4000, 1928, 308...
Male      [5849, 4583, 3000, 2583, 6000, 5417, 2333, 303...
Name: ApplicantIncome, dtype: object

# Descriptive Statistics using Mall Customers Dataset

## Import required libraries

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load the dataset

In [16]:
df= pd.read_csv('Mall_Customers.csv')

## Display dataset

In [17]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## Data Preprocessing

In [18]:
# Display column names
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

In [19]:
# Display data types
df.dtypes

CustomerID                int64
Gender                      str
Age                       int64
Annual Income (k$)        int64
Spending Score (1-100)    int64
dtype: object

In [20]:
# Check for null values
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

## DESCRIPTIVE STATISTICS

In [24]:
# Define bins (age ranges)
bins = [0,20,30,40,50,60,100]
# Define labels for each bin
labels = [ "Teen", "Young Adult","Adult","Middle Age","Senior","Elder"]
df['Age_group']= pd.cut(df['Age'],bins=bins,labels=labels, right=True)
df[['Age','Age_group']].head()

   Age    Age_group
0   19         Teen
1   21  Young Adult
2   20         Teen
3   23  Young Adult
4   31        Adult

In [26]:
# Calculate standard deviation of Spending Score
std_dev = df.groupby('Age_group', observed=False)['Spending Score (1-100)'].std()

print("\nStandard Deviation by Age Group:")
print(std_dev)

Standard Deviation by Age Group:
Age_group
Teen           25.211459
Young Adult    19.932715
Adult          28.875243
Middle Age     15.931508
Senior         20.088146
Elder          14.858648
Name: Spending Score (1-100), dtype: float64

In [36]:
# Group by Age_Group
grouped = df.groupby('Age_group', observed=False)['Spending Score (1-100)']

# Calculate summary statistics
summary = grouped.agg(['mean', 'median', 'min', 'max', 'std'])

print("\nSummary Statistics:")
print(summary)

Summary Statistics:
                  mean  median  min  max        std
Age_group
Teen         44.647059    49.0    5   92  25.211459
Young Adult  67.222222    73.0   12   97  19.932715
Adult        57.500000    61.0    1   99  28.875243
Middle Age   34.394737    37.5    5   59  15.931508
Senior       32.521739    35.0    4   60  20.088146
Elder        44.176471    48.0    3   59  14.858648

In [37]:
# Detailed statistics
print("\nFull Description:")
print(grouped.describe())

Full Description:
             count       mean        std   min    25%   50%    75%   max
Age_group
Teen          17.0  44.647059  25.211459   5.0  39.00  49.0  59.00  92.0
Young Adult   45.0  67.222222  19.932715  12.0  52.00  73.0  82.00  97.0
Adult         60.0  57.500000  28.875243   1.0  35.00  61.0  80.50  99.0
Middle Age    38.0  34.394737  15.931508   5.0  17.75  37.5  46.75  59.0
Senior        23.0  32.521739  20.088146   4.0  14.00  35.0  49.50  60.0
Elder         17.0  44.176471  14.858648   3.0  43.00  48.0  52.00  59.0

## Group Data by Categorical Variable

In [40]:
# create the group
grouped = df.groupby('Gender')['Spending Score (1-100)']

In [43]:
# summary of group
summary_stats = grouped.agg(['mean','median','min','max','std'])
print("Group Statisctics :\n",summary_stats)

Group Statisctics :
              mean  median  min  max       std
Gender
Female  51.526786    50.0    5   99  24.11495
Male    48.511364    50.0    1   97  27.89677

In [45]:
# Detailed statistics
grouped.describe()

        count       mean       std  min   25%   50%   75%   max
Gender
Female  112.0  51.526786  24.11495  5.0  35.0  50.0  73.0  99.0
Male     88.0  48.511364  27.89677  1.0  24.5  50.0  70.0  97.0

## PART B: Iris Dataset Analysis

## Load dataset

In [69]:
df= pd.read_csv('IRIS.csv')

## Display data

In [70]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Check Species

In [71]:
# Unique species
species=df['species'].unique()
print(species)

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [73]:
# summary of group
summary_stats = df.groupby('species').agg(['count','mean','std','min','max'])
summary_stats 
print(summary_stats)

                sepal_length                            sepal_width         \
                       count   mean       std  min  max       count   mean
species
Iris-setosa               50  5.006  0.352490  4.3  5.8          50  3.418
Iris-versicolor           50  5.936  0.516171  4.9  7.0          50  2.770
Iris-virginica            50  6.588  0.635880  4.9  7.9          50  2.974

                                    petal_length                             \
                      std  min  max        count   mean       std  min  max
species
Iris-setosa      0.381024  2.3  4.4           50  1.464  0.173511  1.0  1.9
Iris-versicolor  0.313798  2.0  3.4           50  4.260  0.469911  3.0  5.1
Iris-virginica   0.322497  2.2  3.8           50  5.552  0.551895  4.5  6.9

                petal_width
                      count   mean       std  min  max
species
Iris-setosa              50  0.244  0.107210  0.1  0.6
Iris-versicolor          50  1.326  0.197753  1.0  1.8
Iris-virginica           50  2.026  0.274650  1.4  2.5

In [75]:
# Detailed statistics
df.groupby('species').describe().T

species             Iris-setosa  Iris-versicolor  Iris-virginica
sepal_length count    50.000000        50.000000       50.000000
             mean      5.006000         5.936000        6.588000
             std       0.352490         0.516171        0.635880
             min       4.300000         4.900000        4.900000
             25%       4.800000         5.600000        6.225000
             50%       5.000000         5.900000        6.500000
             75%       5.200000         6.300000        6.900000
             max       5.800000         7.000000        7.900000
sepal_width  count    50.000000        50.000000       50.000000
             mean      3.418000         2.770000        2.974000
             std       0.381024         0.313798        0.322497
             min       2.300000         2.000000        2.200000
             25%       3.125000         2.525000        2.800000
             50%       3.400000         2.800000        3.000000
             75%       3.675000         3.000000        3.175000
             max       4.400000         3.400000        3.800000
petal_length count    50.000000        50.000000       50.000000
             mean      1.464000         4.260000        5.552000
             std       0.173511         0.469911        0.551895
             min       1.000000         3.000000        4.500000
             25%       1.400000         4.000000        5.100000
             50%       1.500000         4.350000        5.550000
             75%       1.575000         4.600000        5.875000
             max       1.900000         5.100000        6.900000
petal_width  count    50.000000        50.000000       50.000000
             mean      0.244000         1.326000        2.026000
             std       0.107210         0.197753        0.274650
             min       0.100000         1.000000        1.400000
             25%       0.200000         1.200000        1.800000
             50%       0.200000         1.300000        2.000000
             75%       0.300000         1.500000        2.300000
             max       0.600000         1.800000        2.500000