**Import library**

In [25]:
import numpy as np
import pandas as pd

**Import Data CSV and Display data**

In [26]:
df  = pd.read_csv("archive/Mall_Customers.csv")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [27]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

**Display Data Type Of Column**

In [28]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [29]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

**Check Display Null Value in dataSet**

In [30]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

- **Descriptive Statistic**

  - **Create the group Age Wise**

In [31]:
bins =[0,20,30,40,50,60,100]
labels = [
    "0–20",
    "21–30",
    "31–40",
    "41–50",
    "51–60",
    "61–100"
]



df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=True)

In [32]:
std_dev_by_age_range = df.groupby('Age_Group')['Spending Score (1-100)'].std()
print(std_dev_by_age_range )

Age_Group
0–20      25.211459
21–30     19.932715
31–40     28.875243
41–50     15.931508
51–60     20.088146
61–100    14.858648
Name: Spending Score (1-100), dtype: float64

C:\Users\Prathamesh\AppData\Local\Temp\ipykernel_4916\609131501.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  std_dev_by_age_range = df.groupby('Age_Group')['Spending Score (1-100)'].std()

In [33]:
grouped = df.groupby("Age_Group")['Spending Score (1-100)']
grouped.describe()

C:\Users\Prathamesh\AppData\Local\Temp\ipykernel_4916\689249320.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby("Age_Group")['Spending Score (1-100)']

           count       mean        std   min    25%   50%    75%   max
Age_Group
0–20        17.0  44.647059  25.211459   5.0  39.00  49.0  59.00  92.0
21–30       45.0  67.222222  19.932715  12.0  52.00  73.0  82.00  97.0
31–40       60.0  57.500000  28.875243   1.0  35.00  61.0  80.50  99.0
41–50       38.0  34.394737  15.931508   5.0  17.75  37.5  46.75  59.0
51–60       23.0  32.521739  20.088146   4.0  14.00  35.0  49.50  60.0
61–100      17.0  44.176471  14.858648   3.0  43.00  48.0  52.00  59.0

In [35]:
grouped = df.groupby("Age_Group")
grouped.describe().T

C:\Users\Prathamesh\AppData\Local\Temp\ipykernel_4916\3475009189.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby("Age_Group")

Age_Group                           0–20       21–30       31–40       41–50  \
CustomerID             count   17.000000   45.000000   60.000000   38.000000
                       mean    81.117647   93.111111  119.000000  105.026316
                       std     49.364565   62.687980   61.629016   52.243963
                       min      1.000000    2.000000    5.000000   23.000000
                       25%     40.000000   36.000000   65.750000   58.750000
                       50%     92.000000   96.000000  136.000000   98.000000
                       75%    115.000000  146.000000  169.250000  150.000000
                       max    163.000000  200.000000  199.000000  197.000000
Age                    count   17.000000   45.000000   60.000000   38.000000
                       mean    19.058824   25.800000   34.933333   46.605263
                       std      0.747545    3.101319    2.950821    2.726640
                       min     18.000000   21.000000   31.000000   41.000000
                       25%     19.000000   23.000000   32.000000   45.000000
                       50%     19.000000   26.000000   35.000000   47.000000
                       75%     20.000000   29.000000   37.250000   49.000000
                       max     20.000000   30.000000   40.000000   50.000000
Annual Income (k$)     count   17.000000   45.000000   60.000000   38.000000
                       mean    51.117647   56.755556   68.633333   63.605263
                       std     20.563567   28.251432   29.168689   24.152152
                       min     15.000000   15.000000   17.000000   25.000000
                       25%     37.000000   33.000000   46.750000   44.250000
                       50%     59.000000   60.000000   72.500000   60.500000
                       75%     65.000000   77.000000   87.000000   77.750000
                       max     81.000000  137.000000  137.000000  126.000000
Spending Score (1-100) count   17.000000   45.000000   60.000000   38.000000
                       mean    44.647059   67.222222   57.500000   34.394737
                       std     25.211459   19.932715   28.875243   15.931508
                       min      5.000000   12.000000    1.000000    5.000000
                       25%     39.000000   52.000000   35.000000   17.750000
                       50%     49.000000   73.000000   61.000000   37.500000
                       75%     59.000000   82.000000   80.500000   46.750000
                       max     92.000000   97.000000   99.000000   59.000000

Age_Group                          51–60      61–100
CustomerID             count   23.000000   17.000000
                       mean    92.260870   75.176471
                       std     56.035879   33.513496
                       min     13.000000    9.000000
                       25%     55.500000   61.000000
                       50%     75.000000   71.000000
                       75%    135.000000  107.000000
                       max    187.000000  117.000000
Age                    count   23.000000   17.000000
                       mean    55.869565   66.647059
                       std      3.094046    2.148871
                       min     51.000000   63.000000
                       25%     53.500000   65.000000
                       50%     56.000000   67.000000
                       75%     59.000000   68.000000
                       max     60.000000   70.000000
Annual Income (k$)     count   23.000000   17.000000
                       mean    56.695652   50.000000
                       std     23.026536   14.313455
                       min     20.000000   19.000000
                       25%     43.500000   46.000000
                       50%     54.000000   49.000000
                       75%     73.000000   63.000000
                       max    101.000000   65.000000
Spending Score (1-100) count   23.000000   17.000000
                       mean    32.521739   44.176471
                       std     20.088146   14.858648
                       min      4.000000    3.000000
                       25%     14.000000   43.000000
                       50%     35.000000   48.000000
                       75%     49.500000   52.000000
                       max     60.000000   59.000000

***PART B***

- **statistical details for IRIS flowers Specie's**

**Import library**

In [12]:
import numpy as np
import pandas as pd

**Import Data CSV and Display data**

In [13]:
df = pd.read_csv("archive/IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [14]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [15]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [16]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

**Check Display Null Value in dataSet**

In [17]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

**

In [18]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

 **List of species to analyze**

In [21]:
species_list = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
# Group by species and calculate mean and standard deviation for all features
grouped_stats = df.groupby('species').agg(['mean', 'std', 'median'])
print(grouped_stats)

                sepal_length                  sepal_width                   \
                        mean       std median        mean       std median
species
Iris-setosa            5.006  0.352490    5.0       3.418  0.381024    3.4
Iris-versicolor        5.936  0.516171    5.9       2.770  0.313798    2.8
Iris-virginica         6.588  0.635880    6.5       2.974  0.322497    3.0

                petal_length                  petal_width
                        mean       std median        mean       std median
species
Iris-setosa            1.464  0.173511   1.50       0.244  0.107210    0.2
Iris-versicolor        4.260  0.469911   4.35       1.326  0.197753    1.3
Iris-virginica         5.552  0.551895   5.55       2.026  0.274650    2.0

In [23]:
grouped_stats = df.groupby('species')
grouped_stats.describe().T

species             Iris-setosa  Iris-versicolor  Iris-virginica
sepal_length count    50.000000        50.000000       50.000000
             mean      5.006000         5.936000        6.588000
             std       0.352490         0.516171        0.635880
             min       4.300000         4.900000        4.900000
             25%       4.800000         5.600000        6.225000
             50%       5.000000         5.900000        6.500000
             75%       5.200000         6.300000        6.900000
             max       5.800000         7.000000        7.900000
sepal_width  count    50.000000        50.000000       50.000000
             mean      3.418000         2.770000        2.974000
             std       0.381024         0.313798        0.322497
             min       2.300000         2.000000        2.200000
             25%       3.125000         2.525000        2.800000
             50%       3.400000         2.800000        3.000000
             75%       3.675000         3.000000        3.175000
             max       4.400000         3.400000        3.800000
petal_length count    50.000000        50.000000       50.000000
             mean      1.464000         4.260000        5.552000
             std       0.173511         0.469911        0.551895
             min       1.000000         3.000000        4.500000
             25%       1.400000         4.000000        5.100000
             50%       1.500000         4.350000        5.550000
             75%       1.575000         4.600000        5.875000
             max       1.900000         5.100000        6.900000
petal_width  count    50.000000        50.000000       50.000000
             mean      0.244000         1.326000        2.026000
             std       0.107210         0.197753        0.274650
             min       0.100000         1.000000        1.400000
             25%       0.200000         1.200000        1.800000
             50%       0.200000         1.300000        2.000000
             75%       0.300000         1.500000        2.300000
             max       0.600000         1.800000        2.500000